import type { User, SamaritanAlert, Business } from "./types";

export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "João Silva",
    email: "joao@example.com",
    phone: "(11) 98765-4321",
    profession: "Eletricista",
    bio: "Membro ativo da comunidade",
    helpOffer: "Ajudo com pequenos consertos elétricos e instalações",
    availabilityStatus: "mesa-posta",
    isOnline: true,
    friends: ["user-2", "user-3"],
    churchId: "church-1",
    createdAt: new Date().toISOString(),
    location: { lat: -23.5505, lng: -46.6333 },
  },
  {
    id: "user-2",
    name: "Maria Santos",
    email: "maria@example.com",
    phone: "(11) 99876-5432",
    profession: "Enfermeira",
    bio: "Dedicada ao cuidado da comunidade",
    helpOffer: "Estou disponível para orar com idosos e visitas de conforto",
    availabilityStatus: "requer-aviso",
    isOnline: true,
    friends: ["user-1", "user-4"],
    churchId: "church-1",
    createdAt: new Date().toISOString(),
    location: { lat: -23.555, lng: -46.628 },
  },
  {
    id: "user-3",
    name: "Pedro Oliveira",
    email: "pedro@example.com",
    phone: "(11) 97654-3210",
    profession: "Pastor",
    bio: "Liderança espiritual",
    helpOffer: "Aconselamento espiritual e liderança de grupos de oração",
    availabilityStatus: "mesa-posta",
    isOnline: true,
    friends: ["user-1"],
    churchId: "church-1",
    createdAt: new Date().toISOString(),
    location: { lat: -23.548, lng: -46.635 },
  },
  {
    id: "user-4",
    name: "Ana Costa",
    email: "ana@example.com",
    phone: "(11) 96543-2109",
    profession: "Professora",
    bio: "Educadora comunitária",
    helpOffer: "Aulas de reforço para crianças e auxílio com lições de casa",
    availabilityStatus: "mesa-posta",
    isOnline: false,
    friends: ["user-2"],
    churchId: "church-1",
    createdAt: new Date().toISOString(),
    location: { lat: -23.56, lng: -46.625 },
  },
  {
    id: "user-5",
    name: "Carlos Mendes",
    email: "carlos@example.com",
    phone: "(11) 95432-1098",
    profession: "Carpinteiro",
    bio: "Artesão dedicado",
    helpOffer: "Construção de móveis e pequenos reparos em madeira",
    availabilityStatus: "requer-aviso",
    isOnline: true,
    friends: [],
    churchId: "church-1",
    createdAt: new Date().toISOString(),
    location: { lat: -23.542, lng: -46.642 },
  },
];

export const mockSamaritanAlerts: SamaritanAlert[] = [
  {
    id: "alert-1",
    userId: "user-2",
    userName: "Maria Santos",
    type: "urgency",
    description: "Idosa vizinha passou mal, precisa de ajuda para ir ao hospital",
    location: { lat: -23.555, lng: -46.628 },
    createdAt: new Date(Date.now() - 30 * 60000).toISOString(), // 30 min atrás
    status: "active",
    responses: ["user-1"],
  },
  {
    id: "alert-2",
    userId: "user-3",
    userName: "Pedro Oliveira",
    type: "practical_help",
    description: "Preciso de ajuda para carregar alimentos doados para as famílias necessitadas",
    location: { lat: -23.548, lng: -46.635 },
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(), // 15 min atrás
    status: "active",
    responses: [],
  },
];

export const mockBusinesses: Business[] = [
  {
    id: "biz-1",
    name: "Padaria da Comunidade",
    category: "alimentacao",
    phone: "(11) 3333-1111",
    address: "Rua A, 123",
    location: { lat: -23.552, lng: -46.63 },
    rating: 4.8,
    description: "Padaria tradicional com pães frescos todos os dias",
    communityRecommendations: ["user-1", "user-2", "user-4"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "biz-2",
    name: "Clínica de Saúde Comunitária",
    category: "saude",
    phone: "(11) 3333-2222",
    address: "Rua B, 456",
    location: { lat: -23.558, lng: -46.632 },
    rating: 4.6,
    description: "Atendimento médico com valores acessíveis",
    communityRecommendations: ["user-3", "user-5"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "biz-3",
    name: "Mercado Solidário",
    category: "mercado",
    phone: "(11) 3333-3333",
    address: "Rua C, 789",
    location: { lat: -23.545, lng: -46.638 },
    rating: 4.9,
    description: "Comérço justo com produtos locais",
    communityRecommendations: ["user-1", "user-2", "user-3", "user-4"],
    createdAt: new Date().toISOString(),
  },
];
